# Generated by Django 3.2.16 on 2024-12-25 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20241225_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='title',
        ),
    ]
