# Generated by Django 5.1.4 on 2025-01-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_remove_comment_post_comment_comment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment",
            new_name="post",
        ),
    ]
