# Generated by Django 5.1.4 on 2025-01-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_rename_comment_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="posts_images", verbose_name="Фото"
            ),
        ),
    ]
